import { MigrationInterface, QueryRunner } from "typeorm";

export class ClinicalCoreAndAuditSchema1787836267071 implements MigrationInterface {
    name = 'ClinicalCoreAndAuditSchema1787836267071'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "professional_profiles" DROP CONSTRAINT "FK_professional_profiles_user_id"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_sessions_user_id"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_user_roles_user_id"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_user_roles_role_id"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_role_permissions_role_id"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_role_permissions_permission_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_roles_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_roles_role_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_role_permissions_role_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_role_permissions_permission_id"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('READ', 'CREATE', 'UPDATE', 'DELETE', 'EXPORT', 'ANONYMIZE', 'LOGIN', 'LOGOUT')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "user_name" character varying(200) NOT NULL, "user_role" character varying(50), "action" "public"."audit_logs_action_enum" NOT NULL DEFAULT 'READ', "resource" character varying(100) NOT NULL, "resource_id" character varying(100), "patient_record_number" character varying(50), "details" text, "ip_address" character varying(45), "user_agent" text, "legal_basis" character varying(100) NOT NULL DEFAULT 'TUTELA_DA_SAUDE', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_audit_resource" ON "audit_logs" ("resource", "resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_user" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_created_at" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."medical_record_entries_type_enum" AS ENUM('consultation', 'procedure', 'diagnosis', 'medication', 'exam')`);
        await queryRunner.query(`CREATE TABLE "medical_record_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patient_id" uuid NOT NULL, "type" "public"."medical_record_entries_type_enum" NOT NULL DEFAULT 'consultation', "title" character varying(200) NOT NULL, "description" text NOT NULL, "notes" text, "icd_code" character varying(20), "icd_description" character varying(250), "prescriptions" jsonb, "professional_name" character varying(200) NOT NULL, "professional_council" character varying(50), "sector" character varying(100) NOT NULL DEFAULT 'Ambulatório', "event_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_locked" boolean NOT NULL DEFAULT false, "origin_system" character varying(50) NOT NULL DEFAULT 'NEXOR', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7cfc69d57da589a22681b026de3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_medical_record_patient" ON "medical_record_entries" ("patient_id") `);
        await queryRunner.query(`CREATE TYPE "public"."patient_allergies_severity_enum" AS ENUM('high', 'moderate', 'low')`);
        await queryRunner.query(`CREATE TABLE "patient_allergies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patient_id" uuid NOT NULL, "name" character varying(150) NOT NULL, "severity" "public"."patient_allergies_severity_enum" NOT NULL DEFAULT 'moderate', "reaction" character varying(250) NOT NULL, "reported_date" character varying(30) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3ad7c82be25564a47df337045f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_allergy_patient" ON "patient_allergies" ("patient_id") `);
        await queryRunner.query(`CREATE TYPE "public"."patient_risk_alerts_severity_enum" AS ENUM('high', 'moderate', 'low')`);
        await queryRunner.query(`CREATE TABLE "patient_risk_alerts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patient_id" uuid NOT NULL, "type" character varying(150) NOT NULL, "severity" "public"."patient_risk_alerts_severity_enum" NOT NULL DEFAULT 'moderate', "description" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_528a89ced1546e464bcf0cdc4c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_risk_alert_patient" ON "patient_risk_alerts" ("patient_id") `);
        await queryRunner.query(`CREATE TYPE "public"."patients_gender_enum" AS ENUM('M', 'F', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."patients_status_enum" AS ENUM('admitted', 'outpatient', 'discharged', 'emergency')`);
        await queryRunner.query(`CREATE TYPE "public"."patients_legal_basis_enum" AS ENUM('TUTELA_DA_SAUDE', 'OBRIGACAO_LEGAL', 'CONSENTIMENTO')`);
        await queryRunner.query(`CREATE TABLE "patients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "record_number" character varying(30) NOT NULL, "name" character varying(200) NOT NULL, "social_name" character varying(200), "cpf" character varying(11), "rg" character varying(20), "date_of_birth" date NOT NULL, "gender" "public"."patients_gender_enum" NOT NULL DEFAULT 'OTHER', "blood_type" character varying(5), "weight" numeric(5,2), "height" numeric(5,2), "status" "public"."patients_status_enum" NOT NULL DEFAULT 'outpatient', "sector" character varying(100) NOT NULL DEFAULT 'Ambulatório', "bed" character varying(50), "attending_physician" character varying(200), "phone" character varying(20), "email" character varying(150), "address" text, "convenio_id" uuid, "insurance_name" character varying(100) NOT NULL DEFAULT 'SUS', "insurance_card_number" character varying(50), "legal_basis" "public"."patients_legal_basis_enum" NOT NULL DEFAULT 'TUTELA_DA_SAUDE', "origin_system" character varying(50) NOT NULL DEFAULT 'NEXOR', "external_id" character varying(100), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_61f265653aacc2b19d1dc751fdd" UNIQUE ("record_number"), CONSTRAINT "PK_a7f0b9fcbb3469d5ec0b0aceaa7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_patients_record_number" ON "patients" ("record_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_patients_cpf" ON "patients" ("cpf") `);
        await queryRunner.query(`ALTER TABLE "convenios" ADD CONSTRAINT "UQ_34d8070cf1f668dd197cb5a3720" UNIQUE ("cnpj")`);
        await queryRunner.query(`ALTER TABLE "professional_profiles" ADD CONSTRAINT "UQ_8a5e9c6d0efcf9b3bf700f51fe0" UNIQUE ("cpf")`);
        await queryRunner.query(`ALTER TYPE "public"."professional_profiles_council_type_enum" RENAME TO "professional_profiles_council_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."professional_profiles_council_type_enum" AS ENUM('CRM', 'COREN', 'CRF', 'CRP', 'NONE')`);
        await queryRunner.query(`ALTER TABLE "professional_profiles" ALTER COLUMN "council_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "professional_profiles" ALTER COLUMN "council_type" TYPE "public"."professional_profiles_council_type_enum" USING "council_type"::"text"::"public"."professional_profiles_council_type_enum"`);
        await queryRunner.query(`ALTER TABLE "professional_profiles" ALTER COLUMN "council_type" SET DEFAULT 'NONE'`);
        await queryRunner.query(`DROP TYPE "public"."professional_profiles_council_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "professional_profiles" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD CONSTRAINT "UQ_0692f810e8926469bec26da0d99" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_permissions_resource_action"`);
        await queryRunner.query(`ALTER TYPE "public"."permissions_resource_enum" RENAME TO "permissions_resource_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_resource_enum" AS ENUM('PATIENT', 'RECORD', 'PHARMACY', 'CONVENIO', 'SYSTEM')`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "resource" TYPE "public"."permissions_resource_enum" USING "resource"::"text"::"public"."permissions_resource_enum"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_resource_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."permissions_action_enum" RENAME TO "permissions_action_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_action_enum" AS ENUM('READ', 'CREATE', 'UPDATE', 'DELETE', 'ALL')`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "action" TYPE "public"."permissions_action_enum" USING "action"::"text"::"public"."permissions_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_action_enum_old"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_permissions_resource_action" ON "permissions" ("resource", "action") `);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "professional_profiles" ADD CONSTRAINT "FK_ed5f5b62a353f11b36ceb7e2e8e" FOREIGN KEY ("user_id") REFERENCES "iam_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "iam_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_record_entries" ADD CONSTRAINT "FK_260f238fc9e69a53cebc94f760a" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_allergies" ADD CONSTRAINT "FK_2e8cd29a6e8b7c811beabcbf18d" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_risk_alerts" ADD CONSTRAINT "FK_db12f394ef0b658f4b9d8b2045f" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "iam_users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "patient_risk_alerts" DROP CONSTRAINT "FK_db12f394ef0b658f4b9d8b2045f"`);
        await queryRunner.query(`ALTER TABLE "patient_allergies" DROP CONSTRAINT "FK_2e8cd29a6e8b7c811beabcbf18d"`);
        await queryRunner.query(`ALTER TABLE "medical_record_entries" DROP CONSTRAINT "FK_260f238fc9e69a53cebc94f760a"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "professional_profiles" DROP CONSTRAINT "FK_ed5f5b62a353f11b36ceb7e2e8e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_permissions_resource_action"`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_action_enum_old" AS ENUM('READ', 'CREATE', 'UPDATE', 'DELETE', 'ALL')`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "action" TYPE "public"."permissions_action_enum_old" USING "action"::"text"::"public"."permissions_action_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_action_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."permissions_action_enum_old" RENAME TO "permissions_action_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_resource_enum_old" AS ENUM('PATIENT', 'RECORD', 'PHARMACY', 'SYSTEM', 'CONVENIO')`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "resource" TYPE "public"."permissions_resource_enum_old" USING "resource"::"text"::"public"."permissions_resource_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_resource_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."permissions_resource_enum_old" RENAME TO "permissions_resource_enum"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_permissions_resource_action" ON "permissions" ("resource", "action") `);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7"`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP CONSTRAINT "UQ_0692f810e8926469bec26da0d99"`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "professional_profiles" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."professional_profiles_council_type_enum_old" AS ENUM('CRM', 'COREN', 'CRF', 'CRP', 'NONE')`);
        await queryRunner.query(`ALTER TABLE "professional_profiles" ALTER COLUMN "council_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "professional_profiles" ALTER COLUMN "council_type" TYPE "public"."professional_profiles_council_type_enum_old" USING "council_type"::"text"::"public"."professional_profiles_council_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "professional_profiles" ALTER COLUMN "council_type" SET DEFAULT 'NONE'`);
        await queryRunner.query(`DROP TYPE "public"."professional_profiles_council_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."professional_profiles_council_type_enum_old" RENAME TO "professional_profiles_council_type_enum"`);
        await queryRunner.query(`ALTER TABLE "professional_profiles" DROP CONSTRAINT "UQ_8a5e9c6d0efcf9b3bf700f51fe0"`);
        await queryRunner.query(`ALTER TABLE "convenios" DROP CONSTRAINT "UQ_34d8070cf1f668dd197cb5a3720"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_patients_cpf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_patients_record_number"`);
        await queryRunner.query(`DROP TABLE "patients"`);
        await queryRunner.query(`DROP TYPE "public"."patients_legal_basis_enum"`);
        await queryRunner.query(`DROP TYPE "public"."patients_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."patients_gender_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_risk_alert_patient"`);
        await queryRunner.query(`DROP TABLE "patient_risk_alerts"`);
        await queryRunner.query(`DROP TYPE "public"."patient_risk_alerts_severity_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_allergy_patient"`);
        await queryRunner.query(`DROP TABLE "patient_allergies"`);
        await queryRunner.query(`DROP TYPE "public"."patient_allergies_severity_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_medical_record_patient"`);
        await queryRunner.query(`DROP TABLE "medical_record_entries"`);
        await queryRunner.query(`DROP TYPE "public"."medical_record_entries_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_resource"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`CREATE INDEX "IDX_role_permissions_permission_id" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_role_permissions_role_id" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_roles_role_id" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_roles_user_id" ON "user_roles" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_role_permissions_permission_id" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_role_permissions_role_id" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_user_roles_role_id" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_user_roles_user_id" FOREIGN KEY ("user_id") REFERENCES "iam_users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_sessions_user_id" FOREIGN KEY ("user_id") REFERENCES "iam_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "professional_profiles" ADD CONSTRAINT "FK_professional_profiles_user_id" FOREIGN KEY ("user_id") REFERENCES "iam_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
