services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexor_life
    ports:
      - '5432:5432'
    volumes:
      - nexor_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d nexor_life']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  nexor_pg_data: {}
